[2025-03-12T02:15:46.465+0000] {processor.py:157} INFO - Started process (PID=28) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:15:46.469+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:15:46.477+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:15:46.476+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:15:47.609+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:15:47.605+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:15:47.610+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:15:47.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 1.200 seconds
[2025-03-12T02:16:17.830+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:17.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:16:17.835+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:16:17.835+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:18.121+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:16:18.119+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:16:18.121+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:18.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.322 seconds
[2025-03-12T02:16:48.329+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:48.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:16:48.334+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:16:48.334+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:48.620+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:16:48.618+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:16:48.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:16:48.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.327 seconds
[2025-03-12T02:17:18.817+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:18.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:17:18.823+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:17:18.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:19.116+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:17:19.115+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:17:19.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:19.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.334 seconds
[2025-03-12T02:17:49.312+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:49.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:17:49.318+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:17:49.318+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:49.626+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:17:49.625+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:17:49.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:17:49.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.354 seconds
[2025-03-12T02:18:19.835+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:19.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:18:19.842+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:18:19.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:20.127+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:18:20.126+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:18:20.128+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:20.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.327 seconds
[2025-03-12T02:18:50.328+0000] {processor.py:157} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:50.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:18:50.335+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:18:50.334+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:50.651+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:18:50.650+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:18:50.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:18:50.683+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.362 seconds
[2025-03-12T02:19:20.883+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:20.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:19:20.889+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:19:20.889+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:21.224+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:19:21.223+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:19:21.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:21.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.382 seconds
[2025-03-12T02:19:51.460+0000] {processor.py:157} INFO - Started process (PID=100) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:51.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:19:51.468+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:19:51.468+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:51.866+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:19:51.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:19:51.867+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:19:51.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.440 seconds
[2025-03-12T02:20:22.024+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:22.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:20:22.032+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:20:22.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:22.335+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:20:22.333+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:20:22.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:22.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.352 seconds
[2025-03-12T02:20:52.600+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:52.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:20:52.606+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:20:52.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:53.085+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:20:53.083+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:20:53.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:20:53.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.530 seconds
[2025-03-12T02:21:23.298+0000] {processor.py:157} INFO - Started process (PID=127) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:23.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:21:23.305+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:21:23.305+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:23.665+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:21:23.663+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:21:23.666+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:23.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.419 seconds
[2025-03-12T02:21:53.905+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:53.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:21:53.910+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:21:53.910+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:54.250+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:21:54.249+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:21:54.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:21:54.285+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.388 seconds
[2025-03-12T02:22:24.461+0000] {processor.py:157} INFO - Started process (PID=151) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:24.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:22:24.469+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:22:24.468+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:24.781+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:22:24.779+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:22:24.781+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:24.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.365 seconds
[2025-03-12T02:22:55.009+0000] {processor.py:157} INFO - Started process (PID=160) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:55.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:22:55.014+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:22:55.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:55.368+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:22:55.367+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:22:55.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:22:55.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.397 seconds
[2025-03-12T02:23:25.570+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:25.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:23:25.577+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:23:25.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:25.898+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:23:25.897+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:23:25.899+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:25.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.365 seconds
[2025-03-12T02:23:56.102+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:56.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:23:56.107+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:23:56.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:56.410+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:23:56.408+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:23:56.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:23:56.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.340 seconds
[2025-03-12T02:24:26.623+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:26.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:24:26.630+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:24:26.629+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:26.928+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:24:26.926+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:24:26.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:26.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.342 seconds
[2025-03-12T02:24:57.148+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:57.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:24:57.154+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:24:57.154+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:57.465+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:24:57.464+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:24:57.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:24:57.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.351 seconds
[2025-03-12T02:25:27.654+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:27.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:25:27.660+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:25:27.660+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:27.967+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:25:27.966+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:25:27.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:27.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.350 seconds
[2025-03-12T02:25:58.166+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:58.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:25:58.172+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:25:58.172+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:58.462+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:25:58.460+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:25:58.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:25:58.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.331 seconds
[2025-03-12T02:26:28.652+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:28.655+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:26:28.658+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:26:28.658+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:28.957+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:26:28.956+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:26:28.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:28.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.343 seconds
[2025-03-12T02:26:59.162+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:59.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:26:59.167+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:26:59.167+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:59.596+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:26:59.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:26:59.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:26:59.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.470 seconds
[2025-03-12T02:27:29.779+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:27:29.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:27:29.787+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:27:29.786+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:27:30.183+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:27:30.182+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:27:30.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:27:30.214+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.442 seconds
[2025-03-12T02:28:00.371+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:00.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:28:00.376+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:28:00.376+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:00.673+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:28:00.672+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:28:00.673+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:00.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.336 seconds
[2025-03-12T02:28:30.853+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:30.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:28:30.860+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:28:30.859+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:31.225+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:28:31.224+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:28:31.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:28:31.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.402 seconds
[2025-03-12T02:29:01.405+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:01.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:29:01.411+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:29:01.410+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:01.705+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:29:01.704+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:29:01.705+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:01.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.334 seconds
[2025-03-12T02:29:31.886+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:31.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:29:31.892+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:29:31.892+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:32.195+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:29:32.194+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:29:32.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:29:32.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.341 seconds
[2025-03-12T02:30:02.277+0000] {processor.py:157} INFO - Started process (PID=285) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:02.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:30:02.282+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:30:02.281+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:02.573+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:30:02.572+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:30:02.574+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:02.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.328 seconds
[2025-03-12T02:30:32.757+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:32.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:30:32.763+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:30:32.763+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:33.050+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:30:33.049+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:30:33.051+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:30:33.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.328 seconds
[2025-03-12T02:31:03.250+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:03.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:31:03.255+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:31:03.255+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:03.553+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:31:03.552+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:31:03.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:03.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.347 seconds
[2025-03-12T02:31:33.769+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:33.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:31:33.774+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:31:33.773+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:34.063+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:31:34.062+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:31:34.063+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:31:34.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.331 seconds
[2025-03-12T02:32:04.268+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:04.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:32:04.272+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:32:04.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:04.577+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:32:04.576+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:32:04.577+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:04.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.342 seconds
[2025-03-12T02:32:34.774+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:34.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:32:34.779+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:32:34.779+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:35.066+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:32:35.065+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:32:35.066+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:32:35.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.325 seconds
[2025-03-12T02:33:05.269+0000] {processor.py:157} INFO - Started process (PID=338) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:05.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:33:05.273+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:33:05.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:05.570+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:33:05.569+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:33:05.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:05.600+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.339 seconds
[2025-03-12T02:33:35.775+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:35.778+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:33:35.783+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:33:35.782+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:36.225+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:33:36.223+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:33:36.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:33:36.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.485 seconds
[2025-03-12T02:34:06.406+0000] {processor.py:157} INFO - Started process (PID=357) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:06.407+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:34:06.413+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:34:06.412+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:06.845+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:34:06.844+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:34:06.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:06.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.473 seconds
[2025-03-12T02:34:36.927+0000] {processor.py:157} INFO - Started process (PID=366) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:36.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:34:36.934+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:34:36.934+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:37.248+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:34:37.247+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:34:37.249+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:34:37.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.360 seconds
[2025-03-12T02:35:07.465+0000] {processor.py:157} INFO - Started process (PID=375) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:07.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:35:07.470+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:35:07.470+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:07.773+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:35:07.772+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:35:07.774+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:07.803+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.346 seconds
[2025-03-12T02:35:37.980+0000] {processor.py:157} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:37.982+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:35:37.986+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:35:37.985+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:38.294+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:35:38.293+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:35:38.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:35:38.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.351 seconds
[2025-03-12T02:36:08.514+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:08.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:36:08.519+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:36:08.518+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:08.817+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:36:08.816+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:36:08.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:08.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.340 seconds
[2025-03-12T02:36:39.026+0000] {processor.py:157} INFO - Started process (PID=402) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:39.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:36:39.033+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:36:39.033+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:39.354+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:36:39.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:36:39.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:36:39.394+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.375 seconds
[2025-03-12T02:37:09.569+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:09.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:37:09.576+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:37:09.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:09.893+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:37:09.892+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:37:09.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:09.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.365 seconds
[2025-03-12T02:37:40.099+0000] {processor.py:157} INFO - Started process (PID=419) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:40.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:37:40.104+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:37:40.103+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:40.399+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:37:40.398+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:37:40.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:37:40.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.336 seconds
[2025-03-12T02:38:10.604+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:10.606+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:38:10.610+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:38:10.610+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:10.924+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:38:10.923+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:38:10.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:10.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.358 seconds
[2025-03-12T02:38:41.125+0000] {processor.py:157} INFO - Started process (PID=436) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:41.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:38:41.130+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:38:41.129+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:41.427+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:38:41.426+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:38:41.427+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:38:41.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.338 seconds
[2025-03-12T02:39:11.639+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:11.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:39:11.645+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:39:11.645+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:11.942+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:39:11.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:39:11.942+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:11.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.339 seconds
[2025-03-12T02:39:42.138+0000] {processor.py:157} INFO - Started process (PID=454) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:42.139+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:39:42.143+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:39:42.143+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:42.452+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:39:42.450+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:39:42.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:39:42.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.349 seconds
[2025-03-12T02:40:12.649+0000] {processor.py:157} INFO - Started process (PID=463) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:12.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:40:12.657+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:40:12.656+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:13.073+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:40:13.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:40:13.074+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:13.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.459 seconds
[2025-03-12T02:40:43.161+0000] {processor.py:157} INFO - Started process (PID=472) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:43.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:40:43.170+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:40:43.169+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:43.611+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:40:43.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:40:43.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:40:43.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.495 seconds
[2025-03-12T02:41:13.835+0000] {processor.py:157} INFO - Started process (PID=480) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:13.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:41:13.841+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:41:13.840+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:14.147+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:41:14.145+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:41:14.147+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:14.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.355 seconds
[2025-03-12T02:41:44.356+0000] {processor.py:157} INFO - Started process (PID=489) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:44.358+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:41:44.362+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:41:44.361+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:44.645+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:41:44.644+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:41:44.646+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:41:44.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.326 seconds
[2025-03-12T02:42:14.859+0000] {processor.py:157} INFO - Started process (PID=498) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:14.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:42:14.864+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:42:14.863+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:15.147+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:42:15.145+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:42:15.147+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:15.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.322 seconds
[2025-03-12T02:42:45.352+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:45.354+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:42:45.358+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:42:45.358+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:45.655+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:42:45.654+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:42:45.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:42:45.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.336 seconds
[2025-03-12T02:43:15.847+0000] {processor.py:157} INFO - Started process (PID=516) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:15.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:43:15.855+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:43:15.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:16.192+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:43:16.191+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:43:16.192+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:16.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.383 seconds
[2025-03-12T02:43:46.396+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:46.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:43:46.403+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:43:46.402+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:46.702+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:43:46.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:43:46.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:43:46.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.346 seconds
[2025-03-12T02:44:16.917+0000] {processor.py:157} INFO - Started process (PID=534) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:16.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:44:16.922+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:44:16.922+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:17.228+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:44:17.226+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:44:17.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:17.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.348 seconds
[2025-03-12T02:44:47.433+0000] {processor.py:157} INFO - Started process (PID=543) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:47.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:44:47.439+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:44:47.438+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:47.739+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:44:47.738+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:44:47.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:44:47.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.345 seconds
[2025-03-12T02:45:17.960+0000] {processor.py:157} INFO - Started process (PID=551) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:17.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:45:17.965+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:45:17.965+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:18.288+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:45:18.287+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:45:18.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:18.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.366 seconds
[2025-03-12T02:45:48.524+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:48.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:45:48.531+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:45:48.530+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:48.822+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:45:48.820+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:45:48.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:45:48.851+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.333 seconds
[2025-03-12T02:46:19.041+0000] {processor.py:157} INFO - Started process (PID=570) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:19.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:46:19.047+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:46:19.046+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:19.343+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:46:19.342+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:46:19.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:19.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.337 seconds
[2025-03-12T02:46:49.549+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:49.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:46:49.555+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:46:49.554+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:49.979+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:46:49.978+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:46:49.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:46:50.009+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.466 seconds
[2025-03-12T02:47:20.063+0000] {processor.py:157} INFO - Started process (PID=588) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:20.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:47:20.069+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:47:20.068+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:20.388+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:47:20.387+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:47:20.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:20.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.361 seconds
[2025-03-12T02:47:50.580+0000] {processor.py:157} INFO - Started process (PID=598) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:50.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:47:50.586+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:47:50.585+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:51.008+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:47:51.007+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:47:51.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:47:51.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.465 seconds
[2025-03-12T02:48:21.184+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:21.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:48:21.190+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:48:21.190+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:21.503+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:48:21.502+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:48:21.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:21.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.350 seconds
[2025-03-12T02:48:51.592+0000] {processor.py:157} INFO - Started process (PID=616) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:51.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:48:51.599+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:48:51.599+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:51.910+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:48:51.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:48:51.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:48:51.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.354 seconds
[2025-03-12T02:49:22.116+0000] {processor.py:157} INFO - Started process (PID=624) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:22.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:49:22.122+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:49:22.121+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:22.419+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:49:22.418+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:49:22.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:22.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.337 seconds
[2025-03-12T02:49:52.610+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:52.611+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:49:52.615+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:49:52.615+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:52.918+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:49:52.917+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:49:52.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:49:52.949+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.345 seconds
[2025-03-12T02:50:23.115+0000] {processor.py:157} INFO - Started process (PID=642) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:23.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:50:23.120+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:50:23.120+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:23.413+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:50:23.412+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:50:23.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:23.444+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.335 seconds
[2025-03-12T02:50:53.633+0000] {processor.py:157} INFO - Started process (PID=651) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:53.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:50:53.639+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:50:53.638+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:53.942+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:50:53.941+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:50:53.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:50:53.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.349 seconds
[2025-03-12T02:51:24.148+0000] {processor.py:157} INFO - Started process (PID=660) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:24.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:51:24.153+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:51:24.152+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:24.530+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:51:24.529+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:51:24.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:24.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.419 seconds
[2025-03-12T02:51:54.743+0000] {processor.py:157} INFO - Started process (PID=669) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:54.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:51:54.748+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:51:54.748+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:55.048+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:51:55.047+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:51:55.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:51:55.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.340 seconds
[2025-03-12T02:52:25.265+0000] {processor.py:157} INFO - Started process (PID=678) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:25.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:52:25.270+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:52:25.269+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:25.561+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:52:25.560+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:52:25.562+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:25.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.333 seconds
[2025-03-12T02:52:55.767+0000] {processor.py:157} INFO - Started process (PID=688) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:55.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:52:55.772+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:52:55.772+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:56.056+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:52:56.055+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:52:56.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:52:56.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.326 seconds
[2025-03-12T02:53:26.256+0000] {processor.py:157} INFO - Started process (PID=697) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:26.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:53:26.262+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:53:26.262+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:26.692+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:53:26.690+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:53:26.692+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:26.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.473 seconds
[2025-03-12T02:53:56.772+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:56.774+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:53:56.779+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:53:56.778+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:57.074+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:53:57.073+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:53:57.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:53:57.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.334 seconds
[2025-03-12T02:54:27.285+0000] {processor.py:157} INFO - Started process (PID=715) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:27.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:54:27.293+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:54:27.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:27.755+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:54:27.753+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:54:27.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:27.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.507 seconds
[2025-03-12T02:54:57.828+0000] {processor.py:157} INFO - Started process (PID=729) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:57.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:54:57.839+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:54:57.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:58.134+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:54:58.133+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:54:58.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:54:58.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.340 seconds
[2025-03-12T02:55:28.333+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:28.335+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:55:28.339+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:55:28.338+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:28.691+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:55:28.690+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:55:28.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:28.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.395 seconds
[2025-03-12T02:55:58.911+0000] {processor.py:157} INFO - Started process (PID=746) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:58.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:55:58.918+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:55:58.917+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:59.233+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:55:59.232+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:55:59.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:55:59.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.362 seconds
[2025-03-12T02:56:29.463+0000] {processor.py:157} INFO - Started process (PID=755) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:56:29.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:56:29.470+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:56:29.469+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:56:29.798+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:56:29.797+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:56:29.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:56:29.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.378 seconds
[2025-03-12T02:57:00.011+0000] {processor.py:157} INFO - Started process (PID=764) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:00.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:57:00.017+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:57:00.016+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:00.328+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:57:00.326+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:57:00.328+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:00.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.355 seconds
[2025-03-12T02:57:30.557+0000] {processor.py:157} INFO - Started process (PID=773) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:30.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:57:30.563+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:57:30.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:30.895+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:57:30.893+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:57:30.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:57:30.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.374 seconds
[2025-03-12T02:58:01.104+0000] {processor.py:157} INFO - Started process (PID=783) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:01.106+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:58:01.110+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:58:01.109+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:01.418+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:58:01.417+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:58:01.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:01.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.352 seconds
[2025-03-12T02:58:31.632+0000] {processor.py:157} INFO - Started process (PID=792) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:31.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:58:31.640+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:58:31.639+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:31.967+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:58:31.965+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:58:31.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:58:32.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.374 seconds
[2025-03-12T02:59:02.197+0000] {processor.py:157} INFO - Started process (PID=802) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:02.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:59:02.204+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:59:02.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:02.537+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:59:02.536+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:59:02.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:02.568+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.378 seconds
[2025-03-12T02:59:32.752+0000] {processor.py:157} INFO - Started process (PID=811) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:32.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T02:59:32.760+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:59:32.760+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:33.237+0000] {logging_mixin.py:151} INFO - [2025-03-12T02:59:33.235+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T02:59:33.238+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T02:59:33.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.525 seconds
[2025-03-12T03:00:03.474+0000] {processor.py:157} INFO - Started process (PID=820) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:03.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:00:03.482+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:00:03.481+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:03.837+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:00:03.836+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:00:03.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:03.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.405 seconds
[2025-03-12T03:00:34.079+0000] {processor.py:157} INFO - Started process (PID=829) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:34.082+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:00:34.086+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:00:34.085+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:34.427+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:00:34.426+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:00:34.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:00:34.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.384 seconds
[2025-03-12T03:01:04.654+0000] {processor.py:157} INFO - Started process (PID=838) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:04.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:01:04.663+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:01:04.662+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:05.125+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:01:05.123+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:01:05.125+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:05.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.511 seconds
[2025-03-12T03:01:35.225+0000] {processor.py:157} INFO - Started process (PID=846) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:35.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:01:35.231+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:01:35.231+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:35.567+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:01:35.566+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:01:35.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:01:35.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.381 seconds
[2025-03-12T03:02:05.772+0000] {processor.py:157} INFO - Started process (PID=855) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:05.774+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:02:05.778+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:02:05.777+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:06.081+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:02:06.080+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:02:06.082+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:06.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.346 seconds
[2025-03-12T03:02:36.297+0000] {processor.py:157} INFO - Started process (PID=864) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:36.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:02:36.303+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:02:36.302+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:36.613+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:02:36.611+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:02:36.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:02:36.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.352 seconds
[2025-03-12T03:03:06.841+0000] {processor.py:157} INFO - Started process (PID=873) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:06.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:03:06.847+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:03:06.847+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:07.203+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:03:07.201+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:03:07.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:07.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.401 seconds
[2025-03-12T03:03:37.409+0000] {processor.py:157} INFO - Started process (PID=882) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:37.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:03:37.416+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:03:37.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:37.730+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:03:37.729+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:03:37.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:03:37.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.363 seconds
[2025-03-12T03:04:07.957+0000] {processor.py:157} INFO - Started process (PID=891) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:07.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:04:07.964+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:04:07.963+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:08.354+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:04:08.353+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:04:08.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:08.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.435 seconds
[2025-03-12T03:04:38.559+0000] {processor.py:157} INFO - Started process (PID=900) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:38.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:04:38.564+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:04:38.564+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:38.874+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:04:38.873+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:04:38.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:04:38.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.358 seconds
[2025-03-12T03:05:09.102+0000] {processor.py:157} INFO - Started process (PID=910) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:09.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:05:09.108+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:05:09.107+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:09.435+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:05:09.434+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:05:09.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:09.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.372 seconds
[2025-03-12T03:05:39.641+0000] {processor.py:157} INFO - Started process (PID=919) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:39.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:05:39.647+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:05:39.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:39.951+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:05:39.950+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:05:39.952+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:05:39.984+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.350 seconds
[2025-03-12T03:06:10.186+0000] {processor.py:157} INFO - Started process (PID=927) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:10.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:06:10.194+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:06:10.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:10.637+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:06:10.635+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:06:10.637+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:10.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.485 seconds
[2025-03-12T03:06:40.762+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:40.764+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:06:40.769+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:06:40.768+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:41.103+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:06:41.102+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:06:41.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:06:41.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.379 seconds
[2025-03-12T03:07:11.328+0000] {processor.py:157} INFO - Started process (PID=945) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:11.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:07:11.334+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:07:11.333+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:11.649+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:07:11.648+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:07:11.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:11.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.355 seconds
[2025-03-12T03:07:41.858+0000] {processor.py:157} INFO - Started process (PID=954) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:41.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:07:41.865+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:07:41.864+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:42.324+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:07:42.323+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:07:42.325+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:07:42.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.507 seconds
[2025-03-12T03:08:12.522+0000] {processor.py:157} INFO - Started process (PID=963) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:12.524+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:08:12.528+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:08:12.527+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:12.858+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:08:12.857+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:08:12.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:12.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.373 seconds
[2025-03-12T03:08:43.070+0000] {processor.py:157} INFO - Started process (PID=972) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:43.071+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:08:43.076+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:08:43.075+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:43.378+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:08:43.376+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:08:43.378+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:08:43.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.348 seconds
[2025-03-12T03:09:13.595+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:13.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:09:13.602+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:09:13.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:13.918+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:09:13.916+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-12T03:09:13.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:13.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.363 seconds
[2025-03-12T03:09:44.144+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:44.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:09:44.150+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:09:44.149+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:44.478+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:09:44.477+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 19, in <module>
    from common.bq_queries import *
ModuleNotFoundError: No module named 'common.bq_queries'
[2025-03-12T03:09:44.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:09:44.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.373 seconds
[2025-03-12T03:10:14.706+0000] {processor.py:157} INFO - Started process (PID=999) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:14.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:10:14.712+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:10:14.712+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:15.024+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:10:15.022+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 19, in <module>
    from common.bq_queries import *
ModuleNotFoundError: No module named 'common.bq_queries'
[2025-03-12T03:10:15.024+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:15.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.355 seconds
[2025-03-12T03:10:45.234+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:45.237+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:10:45.241+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:10:45.240+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:45.825+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:10:45.824+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:10:45.826+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:10:45.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.635 seconds
[2025-03-12T03:11:16.053+0000] {processor.py:157} INFO - Started process (PID=1018) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:16.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:11:16.059+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:11:16.059+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:16.502+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:11:16.500+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:11:16.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:16.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.485 seconds
[2025-03-12T03:11:46.719+0000] {processor.py:157} INFO - Started process (PID=1027) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:46.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:11:46.726+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:11:46.725+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:47.185+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:11:47.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:11:47.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:11:47.214+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.502 seconds
[2025-03-12T03:12:17.411+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:17.412+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:12:17.416+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:12:17.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:17.853+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:12:17.852+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:12:17.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:17.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.479 seconds
[2025-03-12T03:12:48.058+0000] {processor.py:157} INFO - Started process (PID=1045) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:48.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:12:48.065+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:12:48.065+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:48.661+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:12:48.660+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:12:48.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:12:48.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.638 seconds
[2025-03-12T03:13:18.731+0000] {processor.py:157} INFO - Started process (PID=1055) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:18.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:13:18.736+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:13:18.736+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:19.164+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:13:19.163+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:13:19.165+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:19.190+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.466 seconds
[2025-03-12T03:13:49.369+0000] {processor.py:157} INFO - Started process (PID=1064) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:49.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:13:49.375+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:13:49.375+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:49.798+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:13:49.796+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:13:49.798+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:13:49.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.464 seconds
[2025-03-12T03:14:20.006+0000] {processor.py:157} INFO - Started process (PID=1073) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:20.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:14:20.014+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:14:20.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:20.454+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:14:20.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:14:20.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:20.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.482 seconds
[2025-03-12T03:14:50.639+0000] {processor.py:157} INFO - Started process (PID=1082) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:50.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:14:50.646+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:14:50.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:51.254+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:14:51.252+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:14:51.254+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:14:51.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.649 seconds
[2025-03-12T03:15:21.445+0000] {processor.py:157} INFO - Started process (PID=1091) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:21.447+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:15:21.451+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:15:21.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:21.941+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:15:21.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:15:21.942+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:21.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.531 seconds
[2025-03-12T03:15:52.131+0000] {processor.py:157} INFO - Started process (PID=1100) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:52.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:15:52.137+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:15:52.136+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:52.590+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:15:52.588+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:15:52.590+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:15:52.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.493 seconds
[2025-03-12T03:16:22.666+0000] {processor.py:157} INFO - Started process (PID=1108) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:22.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:16:22.673+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:16:22.672+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:23.122+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:16:23.121+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:16:23.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:23.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.498 seconds
[2025-03-12T03:16:53.360+0000] {processor.py:157} INFO - Started process (PID=1118) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:53.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:16:53.367+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:16:53.367+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:53.795+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:16:53.793+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:16:53.795+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:16:53.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.469 seconds
[2025-03-12T03:17:24.020+0000] {processor.py:157} INFO - Started process (PID=1127) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:24.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:17:24.033+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:17:24.033+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:24.486+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:17:24.484+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:17:24.486+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:24.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.507 seconds
[2025-03-12T03:17:32.572+0000] {processor.py:157} INFO - Started process (PID=1135) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:32.573+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:17:32.577+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:17:32.577+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:33.007+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:17:33.005+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:17:33.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:17:33.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.467 seconds
[2025-03-12T03:18:03.209+0000] {processor.py:157} INFO - Started process (PID=1145) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:03.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:18:03.217+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:18:03.216+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:03.641+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:18:03.640+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:18:03.642+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:03.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.466 seconds
[2025-03-12T03:18:33.837+0000] {processor.py:157} INFO - Started process (PID=1155) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:33.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:18:33.842+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:18:33.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:34.250+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:18:34.249+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:18:34.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:18:34.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.445 seconds
[2025-03-12T03:19:04.453+0000] {processor.py:157} INFO - Started process (PID=1164) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:04.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:19:04.465+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:19:04.465+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:04.901+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:19:04.899+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:19:04.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:04.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.482 seconds
[2025-03-12T03:19:35.100+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:35.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:19:35.105+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:19:35.105+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:35.528+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:19:35.526+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:19:35.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:19:35.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.459 seconds
[2025-03-12T03:20:05.726+0000] {processor.py:157} INFO - Started process (PID=1182) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:05.729+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:20:05.733+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:20:05.732+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:06.167+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:20:06.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:20:06.168+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:06.196+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.475 seconds
[2025-03-12T03:20:36.368+0000] {processor.py:157} INFO - Started process (PID=1191) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:36.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:20:36.374+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:20:36.373+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:36.798+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:20:36.797+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:20:36.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:20:36.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.463 seconds
[2025-03-12T03:21:07.002+0000] {processor.py:157} INFO - Started process (PID=1200) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:07.004+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:21:07.008+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:21:07.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:07.431+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:21:07.429+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:21:07.431+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:07.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.466 seconds
[2025-03-12T03:21:37.630+0000] {processor.py:157} INFO - Started process (PID=1209) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:37.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:21:37.635+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:21:37.635+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:38.089+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:21:38.087+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:21:38.089+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:21:38.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.489 seconds
[2025-03-12T03:22:08.299+0000] {processor.py:157} INFO - Started process (PID=1218) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:08.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:22:08.305+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:22:08.305+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:08.724+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:22:08.723+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:22:08.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:08.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.458 seconds
[2025-03-12T03:22:38.917+0000] {processor.py:157} INFO - Started process (PID=1227) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:38.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-12T03:22:38.924+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:22:38.924+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:39.332+0000] {logging_mixin.py:151} INFO - [2025-03-12T03:22:39.331+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
  File "/opt/airflow/common/file_config.py", line 8, in <module>
    with open('common/config.yaml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'common/config.yaml'
[2025-03-12T03:22:39.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-12T03:22:39.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 0.445 seconds
