[2025-03-21T14:20:39.306+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_ingestion_gcs_dag.download_cards_dataset manual__2025-03-21T14:20:35.898182+00:00 [queued]>
[2025-03-21T14:20:39.328+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_ingestion_gcs_dag.download_cards_dataset manual__2025-03-21T14:20:35.898182+00:00 [queued]>
[2025-03-21T14:20:39.329+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-21T14:20:39.358+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_cards_dataset> on 2025-03-21 14:20:35.898182+00:00
[2025-03-21T14:20:39.373+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2025-03-21T14:20:39.384+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_ingestion_gcs_dag', 'download_cards_dataset', 'manual__2025-03-21T14:20:35.898182+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/etl_ingest_tables.py', '--cfg-path', '/tmp/tmpt7p4wv4m']
[2025-03-21T14:20:39.393+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask download_cards_dataset
[2025-03-21T14:20:39.508+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_ingestion_gcs_dag.download_cards_dataset manual__2025-03-21T14:20:35.898182+00:00 [running]> on host 76faeac9fcab
[2025-03-21T14:20:39.703+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dimension_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_cards_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T14:20:35.898182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T14:20:35.898182+00:00'
[2025-03-21T14:20:39.708+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T14:20:39.710+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://github.com/LilyTao123/financial-transaction-data/releases/download/card/cards_data.csv > /opt/***/temp_data/dimension/cards/cards.csv']
[2025-03-21T14:20:39.740+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T14:20:39.746+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/temp_data/dimension/cards/cards.csv: No such file or directory
[2025-03-21T14:20:39.748+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-21T14:20:39.784+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-21T14:20:39.794+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dimension_ingestion_gcs_dag, task_id=download_cards_dataset, execution_date=20250321T142035, start_date=20250321T142039, end_date=20250321T142039
[2025-03-21T14:20:39.826+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 176 for task download_cards_dataset (Bash command failed. The command returned a non-zero exit code 1.; 206)
[2025-03-21T14:20:39.884+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T14:20:39.950+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
