[2025-03-21T15:22:08.979+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.download_trsction_dataset manual__2025-03-21T15:22:01.999163+00:00 [queued]>
[2025-03-21T15:22:08.997+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.download_trsction_dataset manual__2025-03-21T15:22:01.999163+00:00 [queued]>
[2025-03-21T15:22:08.998+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-21T15:22:09.027+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_trsction_dataset> on 2025-03-21 15:22:01.999163+00:00
[2025-03-21T15:22:09.040+0000] {standard_task_runner.py:57} INFO - Started process 1241 to run task
[2025-03-21T15:22:09.048+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trnsaction_ingestion_gcs_dag', 'download_trsction_dataset', 'manual__2025-03-21T15:22:01.999163+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/etl_trsction_table.py', '--cfg-path', '/tmp/tmpgxyvhk_z']
[2025-03-21T15:22:09.055+0000] {standard_task_runner.py:85} INFO - Job 199: Subtask download_trsction_dataset
[2025-03-21T15:22:09.155+0000] {task_command.py:415} INFO - Running <TaskInstance: trnsaction_ingestion_gcs_dag.download_trsction_dataset manual__2025-03-21T15:22:01.999163+00:00 [running]> on host 76faeac9fcab
[2025-03-21T15:22:09.323+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trnsaction_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_trsction_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T15:22:01.999163+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T15:22:01.999163+00:00'
[2025-03-21T15:22:12.437+0000] {logging_mixin.py:151} INFO - âœ… Dataset downloaded to /opt/***/temp_data/trnsction/transactions_data.zip
[2025-03-21T15:22:12.438+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_dimension.py", line 56, in download_dataset
    os.makedirs(extract_path, exist_ok=True)
NameError: name 'os' is not defined
[2025-03-21T15:22:12.454+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trnsaction_ingestion_gcs_dag, task_id=download_trsction_dataset, execution_date=20250321T152201, start_date=20250321T152208, end_date=20250321T152212
[2025-03-21T15:22:12.479+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 199 for task download_trsction_dataset (name 'os' is not defined; 1241)
[2025-03-21T15:22:12.528+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T15:22:12.595+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
