[2025-03-11T17:35:29.490+0000] {processor.py:157} INFO - Started process (PID=98) to work on /opt/airflow/dags/etl_initialise.py
[2025-03-11T17:35:29.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_initialise.py for tasks to queue
[2025-03-11T17:35:29.496+0000] {logging_mixin.py:151} INFO - [2025-03-11T17:35:29.495+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/etl_initialise.py
[2025-03-11T17:35:31.784+0000] {logging_mixin.py:151} INFO - [2025-03-11T17:35:31.782+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/etl_initialise.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_initialise.py", line 18, in <module>
    from common.file_config import *
ModuleNotFoundError: No module named 'common.file_config'
[2025-03-11T17:35:31.785+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_initialise.py
[2025-03-11T17:35:31.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_initialise.py took 2.337 seconds
